server:
    port: 4204              # run the server on port
    name: "musick"          # base name of the HTTP address
  
  lastfm:
    apiKey: "xxx"
    apiSecret: "xxx"
    username: "architkhode"
  