{
 "title": "Musick",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate by route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_total{job=\"musick\"}[1m])) by (instance, route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "LastFM Polling Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "musick_lastfm_polling_count" }
   ]
  },
  {
   "title": "# of goroutines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"musick\"}"
    }
   ]
  },
  {
   "title": "LastFM Polling Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "musick_lastfm_polling_error_count"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"musick\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"musick\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"musick\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"musick\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"musick\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}